export const WEBCHAT_CONFIGURATION = {
    ENVIRONMENT: 'ENVIRONMENT_URL',
    BOT_ID: 'YOUR_BOT_ID',
    BOT_TOKEN: 'YOUR_BOT_TOKEN',
    INTERLOCUTOR_ID: 'YOUR_INTERLOCuTOR_ID',
    SOCKET_TOKEN: 'YOUR_INTERLOCUTOR_SOCKET_TOKEN'
};
